### PR TITLE
fixed Content model and serializing booleans

### PR DESCRIPTION
**Pull request by davearata**
This fixes the content model being deserialized during a response as well as serializing booleans when creating objects.

### CODE REVIEW

**Comment by uberhacker** [comment]
Hey @davearata: Thanks for the PR!  It looks good but I'm a bit confused by Ethan's email which mentions setting values to null instead of an empty string.  I'm guessing he means I should change values in `apprise_mobile_api.module`?  That file wasn't changed in this PR.  Should we just merge this and add another PR with those changes?  See Ethan's response below:
```
Hi Liyan,

Our engineering team was able to make some headway. We figured out that your access to the API was failing when php was trying to serialize and deserialize the request and response objects. 

We created a pull request to your GitHub that you can find in the link below. Also, to test, we simplified your request to create content. This is because we were not able to effectively use the plugin to post dynamic content that we created in Drupal. This is probably because of our very lite setup of Drupal. The payload we used to test with is also below. 

One thing to check within your use of the plugin is that it's better to set a value to null instead of an empty string. In most cases, an empty string will be an invalid value for fields. Please let us know if you need anymore information.

$publish_date = null; // format_date($node->created, ‘custom’, ‘Y-m-d H:i’);
           $web_url = ‘http://google.com'; // url(‘node/’ . $node->nid, array(‘absolute’ => TRUE));
           $share = ‘SHARE_DISABLED’;
           $post_date = null; // ‘’;
           $unpost_date = null; // ‘’;
           $notes_enabled = false;
           $notify = true;
           $secure = false;
           $include_in_feed = true;
           $display_thumbnail = true;
           $content_folder = ‘590103e2572aa7fa31c5ce1e’; //$node->field_apprise_mobile_api_folder[LANGUAGE_NONE][0][‘value’];
           $access_groups = null; // array(‘’);
           $integration_id = null; // ‘’;
           $integration_type = null; // ‘’;

https://github.com/uberhacker/apprise_mobile_api/pull/1

Sincerely,
Ethan
```
Thanks

**Comment by davearata** [comment]
Hey @uberhacker 

Sorry for any confusion. I didn't want to make any changes to the part of the plugin that was outside of the code we delivered. Just in case you had the code setup expecting it a certain way. But if you like I can add a commit to the pull request for setting the values to null or you can make it a separate commit to the repo. Let us know which you prefer. 

Best,
Dave

**Comment by uberhacker** [comment]
Hey @davearata: I can go ahead and make the changes and submit a new PR and you can review it.  Will that work?
Thanks

**Comment by davearata** [comment]
Hey @uberhacker sounds like a plan.

Best,
Dave

**Comment by uberhacker** [comment]
Done.  See #2.

**Pull request merged**
